
Training - 1
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=act   --output_dir=~/train/pour_coke_static_act_single_chunk_32 --policy.chunk_size=32 --policy.n_action_steps=32 --policy.use_separate_encoder_per_camera=false --policy.vision_backbone=resnet18 --policy.use_vae=true --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static --save_freq=10000 --steps=100000^C
(lerobot) root@main-wsp-p22qd0eoj3x8-0:~/lerobot# lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=act   --output_dir=~/train1/pour_coke_static_act_single_chunk_32 --policy.chunk_size=32 --policy.n_action_steps=32 --policy.use_separate_encoder_per_camera=false --policy.vision_backbone=resnet18 --policy.use_vae=true --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static --save_freq=10000 --steps=100000
INFO 2026-01-31 23:59:39 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'act',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.9, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 1e-05,
               'type': 'adamw',
               'weight_decay': 0.0001},
 'output_dir': '~/train1/pour_coke_static_act_single_chunk_32',
 'peft': None,
 'policy': {'chunk_size': 32,
            'device': 'cuda',
            'dim_feedforward': 3200,
            'dim_model': 512,
            'dropout': 0.1,
            'feedforward_activation': 'relu',
            'input_features': {},
            'kl_weight': 10.0,
            'latent_dim': 32,
            'license': None,
            'n_action_steps': 32,
            'n_decoder_layers': 1,
            'n_encoder_layers': 4,
            'n_heads': 8,
            'n_obs_steps': 1,
            'n_vae_encoder_layers': 4,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.MEAN_STD: 'MEAN_STD'>},
            'optimizer_lr': 1e-05,
            'optimizer_lr_backbone': 1e-05,
            'optimizer_weight_decay': 0.0001,
            'output_features': {},
            'pre_norm': False,
            'pretrained_backbone_weights': 'ResNet18_Weights.IMAGENET1K_V1',
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'replace_final_stride_with_dilation': False,
            'repo_id': 'anjalidhabaria/pour_coke_static',
            'tags': None,
            'temporal_ensemble_coeff': None,
            'type': 'act',
            'use_amp': False,
            'use_peft': False,
            'use_separate_encoder_per_camera': False,
            'use_vae': True,
            'vision_backbone': 'resnet18'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': None,
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}

Training - 2
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=act   --output_dir=~/train2/pour_coke_static_act_individual_hunk_32_cosine --policy.chunk_size=32 --policy.n_action_steps=32 --policy.use_separate_encoder_per_camera=true --policy.vision_backbone=resnet34 --policy.pretrained_backbone_weights=ResNet34_Weights.IMAGENET1K_V1 --policy.use_vae=true --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_act_individual_chunk_32_cosine --save_freq=10000 --steps=100000 --scheduler.type=diffuser --scheduler.name=cosine --scheduler.num_warmup_steps=500
INFO 2026-02-01 00:14:17 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'act',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.9, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 1e-05,
               'type': 'adamw',
               'weight_decay': 0.0001},
 'output_dir': '~/train2/pour_coke_static_act_individual_hunk_32_cosine',
 'peft': None,
 'policy': {'chunk_size': 32,
            'device': 'cuda',
            'dim_feedforward': 3200,
            'dim_model': 512,
            'dropout': 0.1,
            'feedforward_activation': 'relu',
            'input_features': {},
            'kl_weight': 10.0,
            'latent_dim': 32,
            'license': None,
            'n_action_steps': 32,
            'n_decoder_layers': 1,
            'n_encoder_layers': 4,
            'n_heads': 8,
            'n_obs_steps': 1,
            'n_vae_encoder_layers': 4,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.MEAN_STD: 'MEAN_STD'>},
            'optimizer_lr': 1e-05,
            'optimizer_lr_backbone': 1e-05,
            'optimizer_weight_decay': 0.0001,
            'output_features': {},
            'pre_norm': False,
            'pretrained_backbone_weights': 'ResNet34_Weights.IMAGENET1K_V1',
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'replace_final_stride_with_dilation': False,
            'repo_id': 'anjalidhabaria/pour_coke_static_act_individual_chunk_32_cosine',
            'tags': None,
            'temporal_ensemble_coeff': None,
            'type': 'act',
            'use_amp': False,
            'use_peft': False,
            'use_separate_encoder_per_camera': True,
            'use_vae': True,
            'vision_backbone': 'resnet34'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': None,
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}


Training -3 
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=act   --output_dir=~/train3/pour_coke_static_act_individual_hunk_32_cosine_temp_ensemble --policy.chunk_size=32 --policy.n_action_steps=1 --policy.temporal_ensemble_coeff=0.01 --policy.use_separate_encoder_per_camera=true --policy.vision_backbone=resnet34 --policy.pretrained_backbone_weights=ResNet34_Weights.IMAGENET1K_V1 --policy.use_vae=true --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_act_individual_chunk_32_cosine_temp_ensemble --save_freq=10000 --steps=100000 --scheduler.type=diffuser --scheduler.name=cosine --scheduler.num_warmup_steps=500 
INFO 2026-02-01 00:19:29 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'act',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.9, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 1e-05,
               'type': 'adamw',
               'weight_decay': 0.0001},
 'output_dir': '~/train3/pour_coke_static_act_individual_hunk_32_cosine_temp_ensemble',
 'peft': None,
 'policy': {'chunk_size': 32,
            'device': 'cuda',
            'dim_feedforward': 3200,
            'dim_model': 512,
            'dropout': 0.1,
            'feedforward_activation': 'relu',
            'input_features': {},
            'kl_weight': 10.0,
            'latent_dim': 32,
            'license': None,
            'n_action_steps': 1,
            'n_decoder_layers': 1,
            'n_encoder_layers': 4,
            'n_heads': 8,
            'n_obs_steps': 1,
            'n_vae_encoder_layers': 4,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.MEAN_STD: 'MEAN_STD'>},
            'optimizer_lr': 1e-05,
            'optimizer_lr_backbone': 1e-05,
            'optimizer_weight_decay': 0.0001,
            'output_features': {},
            'pre_norm': False,
            'pretrained_backbone_weights': 'ResNet34_Weights.IMAGENET1K_V1',
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'replace_final_stride_with_dilation': False,
            'repo_id': 'anjalidhabaria/pour_coke_static_act_individual_chunk_32_cosine_temp_ensemble',
            'tags': None,
            'temporal_ensemble_coeff': 0.01,
            'type': 'act',
            'use_amp': False,
            'use_peft': False,
            'use_separate_encoder_per_camera': True,
            'use_vae': True,
            'vision_backbone': 'resnet34'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': None,
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}


Training - 4
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=diffusion   --output_dir=~/train4/pour_coke_static_diffusion_resnet34_ddim_horizon_16_obs_2  --policy.n_obs_steps=2 --policy.noise_scheduler_type=DDIM --policy.vision_backbone=resnet34 --policy.pretrained_backbone_weights=ResNet34_Weights.IMAGENET1K_V1 --policy.use_separate_rgb_encoder_per_camera=True  --policy.use_group_norm=false --policy.crop_shape=null --policy.crop_is_random=False --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_diffusion_resnet34_ddim_horizon_16_obs_2 --save_freq=10000 --steps=100000 --scheduler.type=diffuser --scheduler.name=cosine --scheduler.num_warmup_steps=500 --job_name=pour_static_diffusion_resnet34_ddim_horizon_16_obs_2
INFO 2026-02-01 00:50:46 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'pour_static_diffusion_resnet34_ddim_horizon_16_obs_2',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.95, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 0.0001,
               'type': 'adam',
               'weight_decay': 1e-06},
 'output_dir': '~/train4/pour_coke_static_diffusion_resnet34_ddim_horizon_16_obs_2',
 'peft': None,
 'policy': {'beta_end': 0.02,
            'beta_schedule': 'squaredcos_cap_v2',
            'beta_start': 0.0001,
            'clip_sample': True,
            'clip_sample_range': 1.0,
            'crop_is_random': False,
            'crop_shape': None,
            'device': 'cuda',
            'diffusion_step_embed_dim': 128,
            'do_mask_loss_for_padding': False,
            'down_dims': [512, 1024, 2048],
            'drop_n_last_frames': 7,
            'horizon': 16,
            'input_features': {},
            'kernel_size': 5,
            'license': None,
            'n_action_steps': 8,
            'n_groups': 8,
            'n_obs_steps': 2,
            'noise_scheduler_type': 'DDIM',
            'normalization_mapping': {'ACTION': <NormalizationMode.MIN_MAX: 'MIN_MAX'>,
                                      'STATE': <NormalizationMode.MIN_MAX: 'MIN_MAX'>,
                                      'VISUAL': <NormalizationMode.MEAN_STD: 'MEAN_STD'>},
            'num_inference_steps': None,
            'num_train_timesteps': 100,
            'optimizer_betas': [0.95, 0.999],
            'optimizer_eps': 1e-08,
            'optimizer_lr': 0.0001,
            'optimizer_weight_decay': 1e-06,
            'output_features': {},
            'prediction_type': 'epsilon',
            'pretrained_backbone_weights': 'ResNet34_Weights.IMAGENET1K_V1',
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'repo_id': 'anjalidhabaria/pour_coke_static_diffusion_resnet34_ddim_horizon_16_obs_2',
            'scheduler_name': 'cosine',
            'scheduler_warmup_steps': 500,
            'spatial_softmax_num_keypoints': 32,
            'tags': None,
            'type': 'diffusion',
            'use_amp': False,
            'use_film_scale_modulation': True,
            'use_group_norm': False,
            'use_peft': False,
            'use_separate_rgb_encoder_per_camera': True,
            'vision_backbone': 'resnet34'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': {'name': 'cosine', 'num_warmup_steps': 500, 'type': 'diffuser'},
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}

Training- 5
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=diffusion   --output_dir=~/train5/pour_coke_static_diffusion_resnet34_ddim_horizon_32_obs_2  --policy.n_obs_steps=2 --policy.noise_scheduler_type=DDIM --policy.vision_backbone=resnet34 --policy.pretrained_backbone_weights=ResNet34_Weights.IMAGENET1K_V1 --policy.use_separate_rgb_encoder_per_camera=True  --policy.use_group_norm=false --policy.crop_shape=null --policy.crop_is_random=False --policy.horizon=32 --policy.n_action_steps=16 --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_diffusion_resnet34_ddim_horizon_32_obs_2 --save_freq=10000 --steps=100000  --job_name=pour_static_diffusion_resnet34_ddim_horizon_32_obs_2
INFO 2026-02-01 01:07:54 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'pour_static_diffusion_resnet34_ddim_horizon_32_obs_2',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.95, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 0.0001,
               'type': 'adam',
               'weight_decay': 1e-06},
 'output_dir': '~/train5/pour_coke_static_diffusion_resnet34_ddim_horizon_32_obs_2',
 'peft': None,
 'policy': {'beta_end': 0.02,
            'beta_schedule': 'squaredcos_cap_v2',
            'beta_start': 0.0001,
            'clip_sample': True,
            'clip_sample_range': 1.0,
            'crop_is_random': False,
            'crop_shape': None,
            'device': 'cuda',
            'diffusion_step_embed_dim': 128,
            'do_mask_loss_for_padding': False,
            'down_dims': [512, 1024, 2048],
            'drop_n_last_frames': 7,
            'horizon': 32,
            'input_features': {},
            'kernel_size': 5,
            'license': None,
            'n_action_steps': 16,
            'n_groups': 8,
            'n_obs_steps': 2,
            'noise_scheduler_type': 'DDIM',
            'normalization_mapping': {'ACTION': <NormalizationMode.MIN_MAX: 'MIN_MAX'>,
                                      'STATE': <NormalizationMode.MIN_MAX: 'MIN_MAX'>,
                                      'VISUAL': <NormalizationMode.MEAN_STD: 'MEAN_STD'>},
            'num_inference_steps': None,
            'num_train_timesteps': 100,
            'optimizer_betas': [0.95, 0.999],
            'optimizer_eps': 1e-08,
            'optimizer_lr': 0.0001,
            'optimizer_weight_decay': 1e-06,
            'output_features': {},
            'prediction_type': 'epsilon',
            'pretrained_backbone_weights': 'ResNet34_Weights.IMAGENET1K_V1',
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'repo_id': 'anjalidhabaria/pour_coke_static_diffusion_resnet34_ddim_horizon_32_obs_2',
            'scheduler_name': 'cosine',
            'scheduler_warmup_steps': 500,
            'spatial_softmax_num_keypoints': 32,
            'tags': None,
            'type': 'diffusion',
            'use_amp': False,
            'use_film_scale_modulation': True,
            'use_group_norm': False,
            'use_peft': False,
            'use_separate_rgb_encoder_per_camera': True,
            'vision_backbone': 'resnet34'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': {'name': 'cosine', 'num_warmup_steps': 500, 'type': 'diffuser'},
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}

Training- 6
lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=smolvla   --output_dir=~/train6/pour_coke_static_smolvla_train_encoder_chunk_32 --policy.load_vlm_weights=true --policy.freeze_vision_encoder=false --policy.train_expert_only=false  --policy.chunk_size=32 --policy.n_action_steps=32  --batch_size=32 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_smolvla_train_encoder_chunk_32 --save_freq=10000 --steps=100000  --job_name=pour_static_smolvla_train_encoder_chunk_32
INFO 2026-02-01 01:43:36 ot_train.py:195 {'batch_size': 32,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'pour_static_smolvla_train_encoder_chunk_32',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.9, 0.95],
               'eps': 1e-08,
               'grad_clip_norm': 10,
               'lr': 0.0001,
               'type': 'adamw',
               'weight_decay': 1e-10},
 'output_dir': '~/train6/pour_coke_static_smolvla_train_encoder_chunk_32',
 'peft': None,
 'policy': {'adapt_to_pi_aloha': False,
            'add_image_special_tokens': False,
            'attention_mode': 'cross_attn',
            'chunk_size': 32,
            'device': 'cuda',
            'empty_cameras': 0,
            'expert_width_multiplier': 0.75,
            'freeze_vision_encoder': False,
            'input_features': {},
            'license': None,
            'load_vlm_weights': True,
            'max_action_dim': 32,
            'max_period': 4.0,
            'max_state_dim': 32,
            'min_period': 0.004,
            'n_action_steps': 32,
            'n_obs_steps': 1,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.IDENTITY: 'IDENTITY'>},
            'num_expert_layers': -1,
            'num_steps': 10,
            'num_vlm_layers': 16,
            'optimizer_betas': [0.9, 0.95],
            'optimizer_eps': 1e-08,
            'optimizer_grad_clip_norm': 10,
            'optimizer_lr': 0.0001,
            'optimizer_weight_decay': 1e-10,
            'output_features': {},
            'pad_language_to': 'longest',
            'prefix_length': -1,
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'repo_id': 'anjalidhabaria/pour_coke_static_smolvla_train_encoder_chunk_32',
            'resize_imgs_with_padding': [512, 512],
            'rtc_config': None,
            'scheduler_decay_lr': 2.5e-06,
            'scheduler_decay_steps': 30000,
            'scheduler_warmup_steps': 1000,
            'self_attn_every_n_layers': 2,
            'tags': None,
            'tokenizer_max_length': 48,
            'train_expert_only': False,
            'train_state_proj': True,
            'type': 'smolvla',
            'use_amp': False,
            'use_cache': True,
            'use_delta_joint_actions_aloha': False,
            'use_peft': False,
            'vlm_model_name': 'HuggingFaceTB/SmolVLM2-500M-Video-Instruct'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': {'decay_lr': 2.5e-06,
               'num_decay_steps': 30000,
               'num_warmup_steps': 1000,
               'peak_lr': 0.0001,
               'type': 'cosine_decay_with_warmup'},
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}

Training- 7
TRANSFORMERS_FIX_MISTRAL_REGEX=1 lerobot-train --dataset.repo_id=anjalidhabaria/pour_coke_static   --policy.type=groot   --output_dir=~/train_77/pour_coke_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01 --policy.tune_llm=false --policy.tune_visual=true --policy.tune_projector=true --policy.tune_diffusion_model=true --policy.n_action_steps=32 --policy.chunk_size=32 --policy.lora_rank=16 --policy.lora_alpha=32 --policy.lora_dropout=0.1  --batch_size=16 --policy.device=cuda   --wandb.enable=true   --policy.repo_id=anjalidhabaria/pour_coke_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01 --save_freq=10000 --steps=100000  --job_name=pour_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01
INFO 2026-02-01 02:53:20 ot_train.py:195 {'batch_size': 16,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'anjalidhabaria/pour_coke_static',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 20000,
 'job_name': 'pour_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.95, 0.999],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 0.0001,
               'type': 'adamw',
               'weight_decay': 1e-05},
 'output_dir': '~/train_77/pour_coke_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01',
 'peft': None,
 'policy': {'balance_dataset_weights': True,
            'balance_trajectory_weights': True,
            'base_model_path': 'nvidia/GR00T-N1.5-3B',
            'batch_size': 32,
            'chunk_size': 32,
            'dataloader_num_workers': 8,
            'dataset_paths': None,
            'device': 'cuda',
            'embodiment_tag': 'new_embodiment',
            'image_size': [224, 224],
            'input_features': {},
            'license': None,
            'lora_alpha': 32,
            'lora_dropout': 0.1,
            'lora_full_model': False,
            'lora_rank': 16,
            'max_action_dim': 32,
            'max_state_dim': 64,
            'max_steps': 10000,
            'n_action_steps': 32,
            'n_obs_steps': 1,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.IDENTITY: 'IDENTITY'>},
            'optimizer_betas': [0.95, 0.999],
            'optimizer_eps': 1e-08,
            'optimizer_lr': 0.0001,
            'optimizer_weight_decay': 1e-05,
            'output_dir': './tmp/gr00t',
            'output_features': {},
            'pretrained_path': None,
            'private': None,
            'push_to_hub': True,
            'repo_id': 'anjalidhabaria/pour_coke_static_groot_chunk_32_lora_rank_16_alpha_32_dropout_01',
            'report_to': 'wandb',
            'resume': False,
            'save_steps': 1000,
            'tags': None,
            'tokenizer_assets_repo': 'lerobot/eagle2hg-processor-groot-n1p5',
            'tune_diffusion_model': True,
            'tune_llm': False,
            'tune_projector': True,
            'tune_visual': True,
            'type': 'groot',
            'use_amp': False,
            'use_bf16': True,
            'use_peft': False,
            'video_backend': 'decord',
            'warmup_ratio': 0.05},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 10000,
 'scheduler': {'decay_lr': 1e-05,
               'num_decay_steps': 10000,
               'num_warmup_steps': 500,
               'peak_lr': 0.0001,
               'type': 'cosine_decay_with_warmup'},
 'seed': 1000,
 'steps': 100000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}
